### ISSUE TITLE
Implement `Arbitrary` interface

### ISSUE THREAD

**Issue by JelF** [akxcv/any-thing#1]
Haskell QuickCheck library has a factory-like interface `Arbitrary`. I think, generators are nice to implement it. I.e. basicly

```
arrayGenerator<T>: (Arbitrary<T>) => Arbitrary<T[]> = generator => new Arbitrary(function*() {
  const iterator = generator.iterate();

  yield [];
  for(;;) {
    const  length = anyNumber({min: 1, max: 10})
    yield (new Array(length)).map(() => iterator.next())
  }
})
```

Of course, this API could be improved, and i also don't sure, that infinite generators are allowed. Hovewer, generator API is good for arbitrary values, because it allows to specify any edge cases that possible. Note, that generators sequences should be independent, so there should be functional API instead.

```
quickCheck(Float, Float, (a, b) => {
  const c = a / b
  expect(a / c).toBe(b)
})
```

Imagine 

```
Arbitrary(Float, function*() {
  yield 0
  yield 1
  for(;;) { yield random() }
}
```

In this case, there are two variables, and their generators should be casterian multiplicated, because we should not loose `b === 0` case

You can learn more about Arbitrary and Coarbitrary monads in QuickCheck in its documentation, but it is a bit complicated. For javascript, i think, implementation with generators is one of the simpliest

**Comment by akxcv** [comment]
I don't intend to reimplement QuickCheck, Anything is just a simple set of generators. Also, there is a library like QuickCheck for JS: [jsverify](https://github.com/jsverify/jsverify).

**Comment by akxcv** [comment]
I've also updated the repo's description, so, hopefully, it will be less confusing now.
